export const PAGINATION = {
    DEFAULT_PAGE: 1,
    DEFAULT_PAGE_SIZE: 10,
    MAX_PAGE_SIZE: 100,
};

export const VOTING_CODE_GENERATION_RETRY_ATTEMPTS = 3;

export const PRESENTATION_SLIDE_EXTRAS_CONFIG_PATHS = {
    ENABLE_MULTIPLE_ANSWERS: "enableMultipleAnswers",
};
